### ISSUE TITLE
Send command do not respect timeout variable

### ISSUE THREAD

**Issue by cynepco3hahue** [google/goexpect#30]
Sometimes, when we have network connectivity issues inside of cluster our tests is stuck on
```
goroutine 20 [chan send, 170 minutes]:
kubevirt.io/kubevirt/vendor/github.com/google/goexpect.(*GExpect).Send(0xc000f96500, 0x15464fb, 0x1, 0xc000d40e68, 0x40d72f)
        /root/go/src/kubevirt.io/kubevirt/vendor/github.com/google/goexpect/expect.go:1093 +0x90
kubevirt.io/kubevirt/vendor/github.com/google/goexpect.(*GExpect).ExpectBatch(0xc000f96500, 0xc000cf0360, 0x9, 0x9, 0x29e8d60800, 0xc000d1d900, 0x3e, 0x0, 0x1711660, 0xc000cb65d0)
        /root/go/src/kubevirt.io/kubevirt/vendor/github.com/google/goexpect/expect.go:595 +0x7b9
kubevirt.io/kubevirt/tests.LoggedInCirrosExpecter(0xc0010b1800, 0xc000c8aa40, 0xc000704f00, 0x0, 0x0)
        /root/go/src/kubevirt.io/kubevirt/tests/utils.go:2069 +0x534
kubevirt.io/kubevirt/tests_test.generateHelloWorldServer(0xc0010b1800, 0x1756360, 0xc000704f00, 0x50, 0x1546d7f, 0x3)
...
```
our `LoggedInCirrosExpecter` uses `ExpectBatch` method with 3 minutes timeout, but it stuck forever if it no input from the expecter.

**Comment by cynepco3hahue** [comment]
Give me know if PR's are welcomed :smile:

**Comment by skalle** [comment]
Very welcome Artyom! :)
